[package]
name = "univiz"
version = "0.1.1"
edition = "2024"

[dependencies]
unicode-segmentation = "1.12.0"
unicode-width = "0.2.2"
colored = "3.0"
unicode_names2 = "2.0.0"
clap = { version = "4.5", features = ["derive"] }
